using System.Collections.Generic;

namespace CafeManagementSystem.DTOs

{

    public class DailySalesReportDto

    {

        // The name of the category (e.g., "Beverages")

        public string Category { get; set; }

        // The sales breakdown for each item in this category.

        public List<ItemSalesDto> Items { get; set; }

        // Total revenue generated by this category.

        public decimal TotalCategoryRevenue { get; set; }

    }

    public class ItemSalesDto

    {

        // The name of the menu item.

        public string ItemName { get; set; }

        // Total quantity sold for the item on the selected day.

        public int QuantitySold { get; set; }

        // Total revenue generated by the item.

        public decimal TotalRevenue { get; set; }

    }

}